### ISSUE TITLE
how can i use this plugin？

### ISSUE THREAD

**Issue by huguang6** [gkjohnson/vscode-urdf-preview#7]
hello gkjohnson, could tell me how can i import this pulgin after installed VSCode?

**Comment by gkjohnson** [comment]
Hi @huguang6!

I haven't published the extension for download, yet, so unfortunately you can't get it through VSCode -- there's still a little bit I'd have to do before making it more widely available.

However, if you're just interested in running it you can download the repo and run it in VSCode through the debug menu.

Can I ask what your interest is in the plugin? If people are interested in using it I may look into publishing it.

Thanks!

**Comment by huguang6** [comment]
i'm glad you answered me!
i want to use URDF in ThreeJS.
recently i study to import URDF in ThreeJS, when i find you demo in github, it's so greate!
i download use it but meet some problem. it can't running directly in local. maybe i need to add threejs lib manually...

**Comment by gkjohnson** [comment]
Have you installed all the npm modules using `npm install`?

If you're just looking to use URDF in THREE.js then the URDFLoader package might be better for you:

https://github.com/gkjohnson/urdf-loaders/tree/master/javascript

It's just a script you can load into a webpage and use like any THREE model loader for URDF files. It's also published to npm so you can just install it!

**Comment by huguang6** [comment]
thank you!
I have solve it,VSCode works in debug mode,
 URDF file is normaly work and 3D graphics are displayed.
